### ISSUE TITLE
[Bug] 3.2 Not running

### ISSUE THREAD

**Issue by keqing114514** [Hartie95/Grasscutter#26]
3.2dont work

**Comment by keqing114514** [comment]
![Uploading -3a9fbf6c2317fe1e.png…]()
![Uploading -4257712b94a8721f.png…]()

**Comment by keqing114514** [comment]
![Uploading -3a9fbf6c2317fe1e.png…]()
![Uploading -4257712b94a8721f.png…]()

**Comment by mjolsic** [comment]
you might wanna try use this res instead. Quest fixes currently only works for a few Monstadt prologue Quest so no point updating res to the latest imo. 
https://github.com/tamilpp25/Grasscutter_Resources

**Comment by keqing114514** [comment]
> you might wanna try use this res instead. Quest fixes currently only works for a few Monstadt prologue Quest so no point updating res to the latest (i.e. 2.7 onwards) imo. https://github.com/tamilpp25/Grasscutter_Resources

I replaced res... but can't use/live all. Can you help me solve this problem

**Comment by Hartie95** [comment]
Whats the error you get with `/give all`? Anything in the console? Do you get at least some items?

Also I'm still on 3.1 with 3.1 resources, and the repository is also still based on 3.1, so no idea if something broke in the never resources.

**Comment by keqing114514** [comment]
> Whats the error you get with `/give all`? Anything in the console? Do you get at least some items?
> 
> Also I'm still on 3.1 with 3.1 resources, and the repository is also still based on 3.1, so no idea if something broke in the never resources.

Please wait, I'll take a screenshot

**Comment by keqing114514** [comment]
> Whats the error you get with `/give all`? Anything in the console? Do you get at least some items?
> 
> Also I'm still on 3.1 with 3.1 resources, and the repository is also still based on 3.1, so no idea if something broke in the never resources.

> Exception in thread "Thread-53" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 6
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at emu.grasscutter.game.avatar.Avatar.unlockConstellation(Avatar.java:770)
        at emu.grasscutter.game.avatar.Avatar.forceConstellationLevel(Avatar.java:816)
        at emu.grasscutter.command.commands.GiveCommand.makeAvatar(GiveCommand.java:226)
        at emu.grasscutter.command.commands.GiveCommand.giveAllAvatars(GiveCommand.java:239)
        at emu.grasscutter.command.commands.GiveCommand.giveAll(GiveCommand.java:429)
        at emu.grasscutter.command.commands.GiveCommand.execute(GiveCommand.java:166)
        at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:310)
        at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "Thread-54" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 6
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at emu.grasscutter.game.avatar.Avatar.unlockConstellation(Avatar.java:770)
        at emu.grasscutter.game.avatar.Avatar.forceConstellationLevel(Avatar.java:816)
        at emu.grasscutter.command.commands.GiveCommand.makeAvatar(GiveCommand.java:226)
        at emu.grasscutter.command.commands.GiveCommand.giveAllAvatars(GiveCommand.java:239)
        at emu.grasscutter.command.commands.GiveCommand.giveAll(GiveCommand.java:429)
        at emu.grasscutter.command.commands.GiveCommand.execute(GiveCommand.java:166)
        at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:310)
        at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "Thread-58" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 6
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at emu.grasscutter.game.avatar.Avatar.unlockConstellation(Avatar.java:770)
        at emu.grasscutter.game.avatar.Avatar.forceConstellationLevel(Avatar.java:816)
        at emu.grasscutter.command.commands.GiveCommand.makeAvatar(GiveCommand.java:226)
        at emu.grasscutter.command.commands.GiveCommand.giveAllAvatars(GiveCommand.java:239)
        at emu.grasscutter.command.commands.GiveCommand.giveAll(GiveCommand.java:429)
        at emu.grasscutter.command.commands.GiveCommand.execute(GiveCommand.java:166)
        at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:310)
        at java.base/java.lang.Thread.run(Thread.java:833)
![Uploading Screenshot_2022-11-09-01-39-04-517_com.miHoYo.GenshinImpact.png…]()

**Comment by Hartie95** [comment]
Oh, maybe its because you have the no element traveler version, which has no constelations, you could try change the element via statue or quest and check if it works then.

**Comment by keqing114514** [comment]
> 



> Oh, maybe its because you have the no element traveler version, which has no constelations, you could try change the element via statue or quest and check if it works then.

> Exception in thread "Thread-28" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 6
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at emu.grasscutter.game.avatar.Avatar.unlockConstellation(Avatar.java:770)
        at emu.grasscutter.game.avatar.Avatar.forceConstellationLevel(Avatar.java:816)
        at emu.grasscutter.command.commands.GiveCommand.makeAvatar(GiveCommand.java:226)
        at emu.grasscutter.command.commands.GiveCommand.giveAllAvatars(GiveCommand.java:239)
        at emu.grasscutter.command.commands.GiveCommand.giveAll(GiveCommand.java:429)
        at emu.grasscutter.command.commands.GiveCommand.execute(GiveCommand.java:166)
        at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:310)
        at java.base/java.lang.Thread.run(Thread.java:833)
![Screenshot_2022-11-09-01-52-04-393_com miHoYo GenshinImpact](https://user-images.githubusercontent.com/116050869/200639480-dcc3f3ce-98b3-41d9-bb57-4c2e63fd4e59.png)

**Comment by keqing114514** [comment]
Please help me.
