### ISSUE TITLE
[Bug] Traveler's skill groupl Bug

### ISSUE THREAD

**Issue by keqing114514** [Hartie95/Grasscutter#28]
When I delete a traveler's individual skill group (in give all), give all is available, so it is a traveler's problem, but I will not fix it

When I use Give > Exception in thread "Thread-23" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 6
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at emu.grasscutter.game.avatar.Avatar.unlockConstellation(Avatar.java:770)
        at emu.grasscutter.game.avatar.Avatar.forceConstellationLevel(Avatar.java:816)
        at emu.grasscutter.command.commands.GiveCommand.makeAvatar(GiveCommand.java:226)
        at emu.grasscutter.command.commands.GiveCommand.giveAllAvatars(GiveCommand.java:239)
        at emu.grasscutter.command.commands.GiveCommand.giveAll(GiveCommand.java:429)
        at emu.grasscutter.command.commands.GiveCommand.execute(GiveCommand.java:166)
        at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:310)
        at java.base/java.lang.Thread.run(Thread.java:833)

When I use /se (Element switch)
> Exception in thread "Thread-22" java.lang.NoSuchMethodError: 'void emu.grasscutter.game.avatar.Avatar.setSkillDepotData(emu.grasscutter.data.excels.AvatarSkillDepotData)'
        at test.gc.switchele.commands.SwitchElement.changeAvatarElement(SwitchElement.java:41)
        at test.gc.switchele.commands.SwitchElement.execute(SwitchElement.java:93)
        at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:310)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by keqing114514** [comment]
Please help me

**Comment by keqing114514** [comment]
Looks like a traveler's problem
